export const SYNC_SESSION = 'SYNC_SESSION';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const SAVE_LOGIN_INFO = 'SAVE_LOGIN_INFO';
export const SET_PHONE_FOR_RESET_PASSWORD = 'SET_PHONE_FOR_RESET_PASSWORD';
export const CLEAR_PHONE_FOR_RESET_PASSWORD = 'CLEAR_PHONE_FOR_RESET_PASSWORD';
export const SET_REVISE_PASSWORD = 'SET_REVISE_PASSWORD';

// home
export const SET_HOT_PLAY = 'SET_HOT_PLAY';
export const SET_HOT_CAR = 'SET_HOT_CAR';
export const SET_HOME_ADVERTISING = 'SET_HOME_ADVERTISING';
export const SET_PROJECT_TYPE = 'SET_PROJECT_TYPE';
export const SET_HOME_BANNER = 'SET_HOME_BANNER';

// project
export const SET_CAMPSITE_SETTING = 'SET_CAMPSITE_SETTING';
export const SET_PROJECT_LIST = 'SET_PROJECT_LIST';
export const SET_PROJECT_INFO = 'SET_PROJECT_INFO';
export const SET_PROJECT_BOOKDETAIL = 'SET_PROJECT_BOOKDETAIL';

// travel
export const SET_TRAVEL_ROUTE_LIST = 'SET_TRAVEL_ROUTE_LIST';
export const SET_TRAVEL_ROUTE_INFO = 'SET_TRAVEL_ROUTE_INFO';
export const SET_TRAVEL_NOTES_LIST = 'SET_TRAVEL_NOTES_LIST';
export const SET_TRAVEL_NOTES_INFO = 'SET_TRAVEL_NOTES_INFO';

// touring-car
export const SET_TOURING_CAR_SETTING = 'SET_TOURING_CAR_SETTING';
export const SET_PICKUP_PLACE_LIST = 'SET_PICKUP_PLACE_LIST';
export const INIT_TOURING_CAR_LIST = 'INIT_TOURING_CAR_LIST';
export const INIT_TOURING_CAR_DATE = 'INIT_TOURING_CAR_DATE';
export const SET_TOURING_CAR_LIST = 'SET_TOURING_CAR_LIST';
export const SET_TOURING_CAR_INFO = 'SET_TOURING_CAR_INFO';
export const SET_TOURING_CAR_DATE = 'SET_TOURING_CAR_DATE';
export const SET_PICKUP_PLACE = 'SET_PICKUP_PLACE';

// album
export const SET_PROJECT_ALBUM = 'SET_PROJECT_ALBUM';
export const SET_CAR_ALBUM = 'SET_CAR_ALBUM';

// notice
export const NEW_NOTICE = 'NEW_NOTICE';
export const CLOSE_NOTICE = 'CLOSE_NOTICE';
export const SET_CAMPER_LIST = 'SET_CAMPER_LIST';

// hotel
export const SET_HOTEL_LIST = 'SET_HOTEL_LIST';

// tourist
export const SET_TOURIST_LIST = 'SET_TOURIST_LIST';
export const ADD_TOURIST = 'ADD_TOURIST';
export const UPDATE_TOURIST = 'UPDATE_TOURIST';
export const DELETE_TOURIST = 'DELETE_TOURIST';

// order
export const MY_ORDER_LIST = 'MY_ORDER_LIST';
export const FC_ORDER_DETAIL = 'FC_ORDER_DETAIL';
export const YW_ORDER_DETAIL = 'YW_ORDER_DETAIL';
export const SET_SPECIAL_REQUIREMENT = 'SET_SPECIAL_REQUIREMENT';
export const SET_ORDER_SCROLLY = 'SET_ORDER_SCROLLY';
export const SET_CANCEL_ORDER_DETAIL = 'SET_CANCEL_ORDER_DETAIL';
export const CANCEL_REASON = 'CANCEL_REASON';
export const SET_IS_COMMENT = 'SET_IS_COMMENT';
export const OTHER_INFO = 'OTHER_INFO';

// order-post
export const SET_ORDER_QUANTITY = 'SET_ORDER_QUANTITY';
export const SET_ORDER_CANTACTINFOS = 'SET_ORDER_CANTACTINFOS';
export const SET_ORDER_CAMPSITE_DATE = 'SET_ORDER_CAMPSITE_DATE';
export const GET_ORDER_CANTACT = 'GET_ORDER_CANTACT';
export const SET_ORDER_SPECIALDEMAND = 'SET_ORDER_SPECIALDEMAND';
export const RESET_ORDER = 'RESET_ORDER';
export const SET_ORDER_TOURCAR_TIME = 'SET_ORDER_TOURCAR_TIME';
export const SET_ORDER_TOURCAR_RETURN = 'SET_ORDER_TOURCAR_RETURN';
export const GET_ORDER_TOURCAR_RETURN = 'GET_ORDER_TOURCAR_RETURN';
export const SET_ORDER_TOURCAR_TOURIST = 'SET_ORDER_TOURCAR_TOURIST';
export const SET_ORDER_RESPONSE = 'SET_ORDER_RESPONSE';

// account
export const ACCOUNT_PROFILE = 'ACCOUNT_PROFILE';
export const SET_ACCOUNT_PROFILE = 'SET_ACCOUNT_PROFILE';
export const SET_ACCOUNT_PROFILE_EMAIL = 'SET_ACCOUNT_PROFILE_EMAIL';
export const SET_DEFAULT_TIME = 'SET_DEFAULT_TIME';
export const SET_LEASTADVANCE_REVERSE_DAY = 'SET_LEASTADVANCE_REVERSE_DAY';
export const SET_ACCOUNT_PROFILE_REALNAME = 'SET_ACCOUNT_PROFILE_REALNAME';
export const SET_ACCOUNT_PROFILE_IDCARD = 'SET_ACCOUNT_PROFILE_IDCARD';
export const DIRVER_TYPE = 'DIRVER_TYPE';
export const DIRVER_AGE = 'DIRVER_AGE';
export const AREA_LIST = 'AREA_LIST';

// comments
export const MY_COMMENTS_LIST = 'MY_COMMENTS_LIST';
export const SET_COMMENT_LIST = 'SET_COMMENT_LIST';
export const SET_TRAVEL_ROUTE_COMMENTS = 'SET_TRAVEL_ROUTE_COMMENTS';
export const SET_TRAVEL_NOTES_COMMENTS = 'SET_TRAVEL_NOTES_COMMENTS';
export const SET_PROJECT_COMMENTS = 'SET_PROJECT_COMMENTS';
export const SET_TOURING_CAR_COMMENTS = 'SET_TOURING_CAR_COMMENTS';
export const REFRESH_COMMENTS = 'REFRESH_COMMENTS';
